apiVersion: v1
kind: Namespace
metadata:
  name: demo-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dpl
  namespace: demo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: demo-pod
#  labels:
#    app: nginx
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#      ports:
#        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: demo-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
